routemap:
  /: en@index
  /no/: no@index

  /about.html: en@about
  /no/om-oss.html: no@about

  /terms.html: en@terms
  /no/betingelser.html: no@terms

  /privacy.html: en@privacy
  /no/personvern.html: no@privacy

  /contact.html: en@contact
  /no/kontakt.html: no@contact

  /upload.html: en@upload
  /no/opplasting.html: no@upload

  /login.html: en@login
  /no/logginn.html: no@login

  /signup.html: en@signup
  /no/nykonto.html: no@signup

  /forgot.html: en@forgot
  /no/glemt.html: no@forgot

  /reset.html: en@reset
  /no/resett.html: no@reset

  /settings.html: en@settings
  /no/bruker.html: no@settings

  /activate.html: en@activate
  /no/aktiver.html: no@activate

  /sites.html: en@sites
  /no/steder.html: no@sites
